### ISSUE TITLE
maven-nodejs-proxy.pvtool.org no longer reachable

### ISSUE THREAD

**Issue by uwesinha** [wcm-io-devops/maven-nodejs-proxy#3]
Effective 2024-02-15, the `nexus.pvtool.org` infrastructure was shut down. As it seems, `maven-nodejs-proxy.pvtool.org` was hosted on the same machine, and was shut down, too. Currently, requests to https://maven-nodejs-proxy.pvtool.org/ run into a timeout. 

Please provide a hosted alternative to `maven-nodejs-proxy.pvtool.org`. If that cannot be done (I'm aware of the motivation that led to the shutdown), please make clear that there will not be a hosted alternative, and that `maven-nodejs-proxy` is only meant for self-hosting.

**Comment by stefanseifert** [comment]
i've already opened an internal ticket (DIT-21527)

**Comment by stefanseifert** [comment]
it's online again - but we have to think about a long-termin solution, maybe the URL will change in the future
